# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: |
        dotnet publish --configuration Release --output ./publish

    - name: Archive published artifacts
      run: |
        cd publish
        tar -czvf published-artifacts.tar.gz *

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: published-artifacts
        path: ./publish/published-artifacts.tar.gz
        retention-days: 1

    - name: Path directory
      run: |
        ls

  send-file:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download published artifacts
      uses: actions/download-artifact@v2
      with:
        name: published-artifacts
        path: ./publish/published-artifacts.tar.gz

    - name: copy file with ssh
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "./publish/published-artifacts.tar.gz"
        target: C:\Projects
  # site-a:
  #   needs: send-file
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: deploy Site-A
  #       uses: appleboy/ssh-action@v1.0.0
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         password: ${{ secrets.PASSWORD }}
  #         script: cd ../../ && cd Site-A && 